name: AWS example workflow
on:
  push
env:
  AWS_REGION : "us-west-2"
  IAM_ROLE: ${{ secrets.IAM_ROLE }}
# permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  TerraformPlan:
    runs-on: ubuntu-latest
    steps:
      - name: git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: GitHubActionSession
          aws-region: ${{ env.AWS_REGION }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: compute letter frequencies
        run: python data/populate_frequences.py

      - name: print letter frequencies
        run: cat data/word_freq_with_pos.csv

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan